FROM registry.access.redhat.com/ubi8/openjdk-11-runtime:latest

ADD --chown=jboss:jboss --chmod=777 https://github.com/Pugmatt/BedrockConnect/releases/latest/download/BedrockConnect-1.0-SNAPSHOT.jar .

EXPOSE 19132/udp