---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: image-build-push
  annotations:
    # How many runs we want to keep.
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
    - name: revision
    - name: image_name
      default: ""
    - name: image_repo_url
      default: http://homelab.nexus.svc:80/homelab
  workspaces:
    - name: source
    - name: basic-auth
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: basic-auth
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
    - name: build-image
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: CONTEXT
          value: ./images/$(params.image_name)
        - name: DOCKERFILE
          value: "./images/$(params.image_name)/Dockerfile"
        - name: IMAGE
          value: "$(params.image_repo_url)/$(params.image_name):test"
