---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: image-build-push
  annotations:
    # How many runs we want to keep.
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
    - name: revision
      default: main
    - name: image_name
    - name: image_repo_url
      default: homelab.docker.homelab.csfreak.com/homelab
  workspaces:
    - name: source
    - name: basic-auth
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: basic-auth
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
    - name: build-image
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: BUILD_EXTRA_ARGS
          value: --build-arg-file=./images/$(tasks.set-image-name.results.image_name)/argfile.conf
        - name: CONTEXT
          value: ./images/$(tasks.set-image-name.results.image_name)
        - name: DOCKERFILE
          value: "./images/$(tasks.set-image-name.results.image_name)/Dockerfile"
        - name: IMAGE
          value: "$(params.image_repo_url)/$(tasks.set-image-name.results.image_name)"
