---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: homelab-images-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"

    # How many runs we want to keep.
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: build_context
      value: plex

  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      - name: build_context
        default: ""
    workspaces:
      - name: source
      - name: basic-auth
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: build-image
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source
        taskRef:
          name: buildah
          kind: ClusterTask
        params:
          - name: CONTEXT
            value: $(params.build_context)
          - name: DOCKERFILE
            value: "$(params.build_context)/Dockerfile"
          - name: IMAGE
            value: "homelab.nexus.svc:80/homelab/$(params.build_context)"

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
