---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: homelab-images-build
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-cel-expression: |
      "images/*".pathChanged()
    # How many runs we want to keep.
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: image_name
      value: ""
    - name: image_repo_url
      value: homelab.docker.homelab.csfreak.com/homelab
    - name: changes
      value: "{{ files }}"
  pipelineRef:
    name: image-build-push
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
