---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: homelab-images-build-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-cel-expression: |
      "images/*".pathChanged()
    # How many runs we want to keep.
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
        default: main
      - name: image_repo_url
        default: homelab.docker.homelab.csfreak.com/homelab
    workspaces:
      - name: source
      - name: basic-auth
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: parse-changes
        runAfter:
          - fetch-repository
        taskRef:
          name: git-parse-changes
        workspaces:
          - name: source
            workspace: source
        params:
          - name: revision
            value: $(params.revision)
          - name: parse_script
            value: "sed -n 's|^images/\\([a-zA-Z0-9-]*\\)/.*|\\1|p'"

      - name: build-image
        workspaces:
          - name: source
            workspace: source
        taskRef:
          name: buildah-image-build
        params:
          - name: IMAGE_REPO
            value: $(params.image_repo_url)
        matrix:
          params:
            - name: IMAGE_NAME
              value: $(tasks.parse-changes.results.changes[*])
    results:
      - name: parsed-images
        type: array
        value: $(tasks.parse-changes.results.changes[*])
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
